version: '3.3'

services:
  db:
    image: mongo
    restart: on-failure
    networks:
      - brainstreamer-net
    ports:
      - "27017:27017"
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data/db

  mq:
    image: rabbitmq
    restart: on-failure
    networks:
      - brainstreamer-net
    ports:
      - "5672:5672"

  base:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-base
    image: brainstreamer-base:latest

  server:
    depends_on:
      - mq
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-server
    restart: on-failure
    networks:
      - brainstreamer-net
    ports:
      - "8000:8000"
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data

  pose-parser:
    depends_on:
      - mq
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-parsers
    restart: on-failure
    networks:
      - brainstreamer-net
    environment:
      - PARSER=pose
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data

  feelings-parser:
    depends_on:
      - mq
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-parsers
    restart: on-failure
    networks:
      - brainstreamer-net
    environment:
      - PARSER=feelings
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data

  depth-image-parser:
    depends_on:
      - mq
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-parsers
    restart: on-failure
    networks:
      - brainstreamer-net
    environment:
      - PARSER=depth_image
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data

  color-image-parser:
    depends_on:
      - mq
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-parsers
    restart: on-failure
    networks:
      - brainstreamer-net
    environment:
      - PARSER=color_image
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data

  saver:
    depends_on:
      - mq
      - db
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-saver
    restart: on-failure
    networks:
      - brainstreamer-net
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data

  api:
    depends_on:
      - db
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-api
    restart: on-failure
    networks:
      - brainstreamer-net
    ports:
      - "5000:5000"
    volumes:
      - brainstreamer-data:/var/data/brainstreamer_data

  gui:
    depends_on:
      - api
      - base
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-gui
    restart: on-failure
    networks:
      - brainstreamer-net
    ports:
      - "8080:8080"


networks:
  brainstreamer-net:

volumes:
  brainstreamer-data: